version: '3.8'

services:
  fastapi_analytic:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "8001:8000"
    restart: always
    container_name: fastapi_analytic
    volumes:
      - ./src:/app/src
    networks:
      - service_network
    environment:
      - PYTHONPATH=/app/src

  mongodb:
    image: mongo:8.0.5-rc2-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/?authSource=admin
    networks:
      - service_network


volumes:
  mongodb_data:

networks:
  service_network:
    external: true
