version: '3.8'

services:
  fastapi_analytic:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "8001:8000"
    restart: always
    container_name: fastapi_analytic
    volumes:
      - ./src:/app/src
    networks:
      - service_network
    environment:
      - PYTHONPATH=/app/src

  mongodb:
    image: mongo:8.0.5-rc2-noble
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - ${MONGODB_EXPRESS_PORT_LOCAL}:${MONGODB_EXPRESS_PORT}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - service_network


volumes:
  mongodb_data:

networks:
  service_network:
    external: true
